name: release-please

on:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_tag: ${{ steps.release.outputs.tag_name }}

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: zachowj/xfinity-data-usage/.github/workflows/publish-docker.yml@main
    secrets: inherit
    with:
      version: ${{ needs.release-please.outputs.release_tag }}
